def complexnesting = {
    <html>
      <head>
        <title/>
      </head>
      <body>
        <div>
          <h1/>
          <div>
            <p>
              <strong/>
            </p>
            <p/>
          </div>
        </div>
        <div/>
      </body>
    </html>
}